name: e_train
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_ui_auth: ^1.8.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
